### PR TITLE
update grunt compile-assets

### PR DESCRIPTION
**Pull request by fuchsnj**

### CODE REVIEW

**Comment by wtcross** [comment]
I think using `bandwidth-{env}-{version}` is a little vague. Did we decide on a name for this library? If it were `bandwidth-phone` then should the compiled asset be `bandwidth-phone-{env}-{version}.js`?

**Comment by wtcross** [comment]
Regarding my last note, how about `bandwidth-webrtc-{env}-{version}.js`?

**Comment by fuchsnj** [comment]
For renaming the file, I'm not opposed to the new name, but we have already started using this in some other libraries. So do you think the name change is important enough to fix this in a few Catapult reference apps?

**Comment by wtcross** [comment]
I'm assuming that the versions those libraries depend on will not go away and so this will not be a breaking change for them. If somebody wants to update to the latest version of `bandwidth-webrtc` then they are going to be in the code anyway.

**Comment by wtcross** [comment]
I vote on going with `bandwidth-webrtc-{env}-{version}`. Any dependent applications need to be updated.

**Comment by wtcross** [comment]
Merging. Nathan said that Catapult staff want to use `bandwidth.js`.

**Pull request merged**
