### PR TITLE
make getUserMedia a public function

### PR DESCRIPTION
**Pull request by fuchsnj**

### CODE REVIEW

**Comment by wtcross** [comment]
`getUserMedia`

**Comment by fuchsnj** [comment]
Making it public allows users to control exactly when the browser asks for media permission, which I have found to be pretty important on RingTo. It also gives users a way to determine the status of the media. After they call this method, it is pending until the promise is resolved, and then the status of the promise determines if media was accepted. So yes, I think users of BWClient should have access to this, since it is pretty important. And it's not like getUserMedia isn't already a public browser API already... this just combines all the browser pre-fixes so the user doesn't have to do it.

**Comment by wtcross** [comment]
Can you include usage example for this in the docs? I think that will be helpful. If you have an example in some repo I'd like to check it out.

**Comment by wtcross** [comment]
Looks good! I'm going to merge once all checks pass.

**Comment by wtcross** [comment]
Coverage is still at 100%, but coveralls didn't report back.

**Pull request merged**
